### ISSUE TITLE
Can't escape semi-colon in yaml templates assertions

### ISSUE THREAD

**Issue by LuisHudson25** [ovh/venom#357] opened 2021-01-20 16:41 UTC
Hello,

I can't achieve to escape semi-colons in yaml templates in assertions, in theory double quote the value should be enough but I can't make it work, either the parser doesn't handle the case or I'm doing a mistake.

I'm using venom v0.27.0 with the following example:
```yaml
version: "2"

name: Test

testcases:
- name: Test
  steps:
  - script: "echo 'a: b'"
    assertions:
    -  result.systemout ShouldEqual "a: b"
    -  result.systemerr ShouldBeEmpty
```

I get the error:
```
error decoding assertions: 1 error(s) decoding:

* 'Assertions[0]' expected type 'string', got unconvertible type 'map[interface {}]interface {}'
```

Thanks you again for your work.
Luis

**Comment by fsamin** [comment] 2021-01-22 15:55
Hello,

I also can reproduce it with the latest release, that i encourage you to test.

I will try to fix it, but as a workaround for now you can to write it this way:

```yaml
name: Test

testcases:
- name: Test
  steps:
  - script: "echo 'a: b'"
    assertions:
    -  "result.systemout ShouldEqual a: b"
    -  result.systemerr ShouldBeEmpty

```

**Comment by LuisHudson25** [comment] 2021-01-22 17:01
Hello @fsamin,

Thank you for your reactivity, I will use the latest release, is it safe to use the 1.0.0-rc ?
I tried a lot of warkaround but I didn't think of this one, thank you !

Luis

**Comment by fsamin** [comment] 2021-01-25 09:44
Hello @LuisHudson25 ,

The 1.0.0-rc-1 is safe but it also introduces some breaking changes. Here are the release notes: https://github.com/ovh/venom/releases/tag/v1.0.0-rc.1

**Comment by LuisHudson25** [comment] 2021-01-29 15:35
Ok I will look at it, thank you !

**Comment by yesnault** [comment] 2021-02-09 20:48
Hi,

In assertions part, it's not possible do use a ':' without escape the whole line. 
This conflicts with the yml engine and the format used by venom for assertions. If you want to use a ':' in assertion, you have to espace the line, to prevent the engine from interpreting this as a dictionary

Other subject, because there is no ':' in the assertion,  but it's now possible to write (without escape the whole line) something like:

```
    -  result.systemout ShouldEqual a b
```
A fix was merged today to allow that, it was not possible before.

**Closed by yesnault** 2021-02-09 20:48 UTC
