### ISSUE TITLE
Cannot check array in json response

### ISSUE THREAD

**Issue by amlwwalker** [ovh/venom#382] opened 2021-03-08 12:05 UTC
In both an exec and HTTP test type, I am getting the same error:

```
    steps:
      - script: echo '{"foo":"bar", "allow_all":false, "some_arr":[]}'
        assertions:
          - result.systemoutjson.allow_all ShouldBeFalse
          - result.systemoutjson.some_arr ShouldBeEmpty
```
response
```
test_1           | Could not access "result.systemoutjson.some_arr" in assertion "result.systemoutjson.some_arr ShouldBeEmpty".
test_1           | This is what we have at "result.systemoutjson":
test_1           | {
test_1           |   "allow_all": false,
test_1           |   "some_arr": [],
test_1           |   "foo": "bar"
test_1           | }
```

Same issue with HTTP test.

Side note: are there any more filled out examples of using tests with http anywhere?

**Comment by yesnault** [comment] 2021-03-08 13:16
Hi @amlwwalker , with which venom version ?

```
❯ cat array.yml
name: Assertions testsuite
testcases:
- name: test assertion
  steps:
  - script: echo '{"foo":"bar", "allow_all":false, "some_arr":[]}' > AA
  - script: echo '{"foo":"bar", "allow_all":false, "some_arr":[]}'
    assertions:
    - result.systemoutjson.allow_all ShouldBeFalse
    - result.systemoutjson.some_arr ShouldBeEmpty
❯ venom run array.yml
 • Assertions testsuite (array.yml)
        • test-assertion SUCCESS
❯ cat AA
{"foo":"bar", "allow_all":false, "some_arr":[]}

**Comment by amlwwalker** [comment] 2021-03-08 13:17
Thanks for rapid response. venom@v0.28.0

For our CICD

**Comment by yesnault** [comment] 2021-03-08 13:18
@amlwwalker  ok. Can you try with latest 1.0.0-rc ?

**Comment by amlwwalker** [comment] 2021-03-08 13:19
For our CICD we are using gobinaries which can only use semver naming i.e beta/rc versions are not strictly semver. When will you be able to release a semver version? Or could you release a 0.9.9 or something?

**Comment by yesnault** [comment] 2021-03-08 13:35
no ok with https://gobinaries.com/ovh/venom/cli/venom@v1.0.0-rc.2 ?

**Comment by amlwwalker** [comment] 2021-03-08 13:37
```
> curl -sf https://gobinaries.com/ovh/venom/cli/venom@v1.0.0-rc.2 | sh

 Error: Repository has no tags matching the requested version
```

**Comment by amlwwalker** [comment] 2021-03-08 13:38
According [to docs
](https://gobinaries.com/)
![image](https://user-images.githubusercontent.com/2920180/110328712-95bf2c80-8013-11eb-8a26-f64385fbe481.png)

**Comment by yesnault** [comment] 2021-03-08 13:41
ok. So, the issue is fixed on rc version, we should release the v1 soon now : a rc version this week and if no issue, the v1 release just after.

**Closed by yesnault** 2021-03-08 13:41 UTC
